class Result:
    def __init__(self, score, BOOKS_NUMBER_MULTIPLIER, SIGNUP_TIME__MULTIPLIER, GETTING_SPEED_MULTIPLIER):
        self.score = score
        self.BOOKS_NUMBER_MULTIPLIER = BOOKS_NUMBER_MULTIPLIER
        self.SIGNUP_TIME__MULTIPLIER = SIGNUP_TIME__MULTIPLIER
        self.GETTING_SPEED_MULTIPLIER = GETTING_SPEED_MULTIPLIER


results = []

